# base image pinned on 2026-07-29 for CVE tracking (W86-C-1 Trivy)
FROM postgres:16.14-alpine

RUN apk add --no-cache \
    gcc \
    make \
    libc-dev \
    perl \
    llvm21 \
    clang21 \
    && mkdir -p /tmp/pgvector \
    && cd /tmp/pgvector \
    && wget https://github.com/pgvector/pgvector/archive/refs/tags/v0.7.0.tar.gz -O v0.7.0.tar.gz \
    && tar xzf v0.7.0.tar.gz \
    && cd pgvector-0.7.0 \
    && make \
    && make install \
    && cd / \
    && rm -rf /tmp/pgvector \
    && apk del gcc make perl llvm21 clang21 libc-dev