FROM postgres:16-alpine

RUN apk add --no-cache \
    build-base \
    postgresql16-dev \
    git \
    && git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git /tmp/pgvector \
    && cd /tmp/pgvector \
    && make \
    && make install \
    && apk del build-base postgresql16-dev git \
    && rm -rf /tmp/pgvector /var/cache/apk/*
