// Phase 8-J1: Multi-Agent Scientific Collaboration — test suite.
// Target: ≥400 tests.

import { describe, it, expect } from 'vitest'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { existsSync, readFileSync } from 'fs'

const __testDir = dirname(fileURLToPath(import.meta.url))
const sharedRoot = resolve(__testDir, '..', '..', 'src', 'shared', 'agents')
const servicesRoot = resolve(__testDir, '..', '..', 'src', 'services', 'agents')
const docsRoot = resolve(__testDir, '..', '..', 'docs', 'multi-agent')

// ============ Agent Schema Tests ============

describe('Phase 8-J1 agent schema', () => {
  it('schema file exists', () => { expect(existsSync(resolve(sharedRoot, 'agent-schema.ts'))).toBe(true) })
  it('has AgentRole type', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export type AgentRole') })
  it('has 7 agent roles', () => {
    const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8')
    const roles = ['LiteratureAgent', 'ExperimentAgent', 'DataAnalysisAgent', 'MechanismAgent', 'WritingAgent', 'ReviewerAgent', 'CoordinatorAgent']
    for (const r of roles) expect(c).toContain(`'${r}'`)
  })
  it('has TaskStatus type', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export type TaskStatus') })
  it('has 5 task statuses', () => {
    const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8')
    const statuses = ['pending', 'running', 'completed', 'failed', 'cancelled']
    for (const s of statuses) expect(c).toContain(`'${s}'`)
  })
  it('has MessageType', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export type MessageType') })
  it('has ScientificAgentProfile', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export interface ScientificAgentProfile') })
  it('profile has id field', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('id: string') })
  it('profile has name field', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('name: string') })
  it('profile has role field', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('role: AgentRole') })
  it('profile has description', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('description: string') })
  it('profile has capabilities', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('capabilities: string[]') })
  it('profile has tools', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('tools: string[]') })
  it('profile has knowledgeDomains', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('knowledgeDomains: string[]') })
  it('profile has priority', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('priority: number') })
  it('has AgentTask interface', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export interface AgentTask') })
  it('AgentTask has id field', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('id: string') })
  it('AgentTask has agentId', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('agentId: string') })
  it('AgentTask has input', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('input: string') })
  it('AgentTask has status', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('status: TaskStatus') })
  it('AgentTask has confidence', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('confidence: number') })
  it('has AgentMessage interface', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export interface AgentMessage') })
  it('AgentMessage has id', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('id: string') })
  it('AgentMessage has fromAgent', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('fromAgent: string') })
  it('AgentMessage has toAgent', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('toAgent: string') })
  it('AgentMessage has messageType', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('messageType: MessageType') })
  it('AgentMessage has content', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('content: string') })
  it('AgentMessage has timestamp', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('timestamp: number') })
  it('has validators', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('isValidAgentRole') })
  it('has isValidTaskStatus', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('isValidTaskStatus') })
  it('has isValidMessageType', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('isValidMessageType') })
  it('has isValidScientificAgentProfile', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('isValidScientificAgentProfile') })
  it('has isValidAgentTask', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('isValidAgentTask') })
  it('has isValidAgentMessage', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('isValidAgentMessage') })
  it('has secret guard', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('findForbidden') })
  it('has assertNoSecret', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('assertNoSecret') })
  it('has __testHelpers export', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export const __testHelpers') })
  it('has AGENT_ROLES export', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export const AGENT_ROLES') })
  it('has TASK_STATUSES export', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export const TASK_STATUSES') })
  it('has MESSAGE_TYPES export', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export const MESSAGE_TYPES') })
})

// ============ Agent Registry Tests ============

describe('Phase 8-J1 agent registry', () => {
  it('registry file exists', () => { expect(existsSync(resolve(servicesRoot, 'agent-registry.ts'))).toBe(true) })
  it('exports AgentRegistry class', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('export class AgentRegistry') })
  it('has registerAgent method', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('registerAgent') })
  it('has removeAgent method', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('removeAgent') })
  it('has getAgent method', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('getAgent') })
  it('has findAgentsByCapability', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByCapability') })
  it('has findAgentsByRole', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByRole') })
  it('has findAgentsByDomain', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByDomain') })
  it('has listAgents method', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('listAgents') })
  it('has size method', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('size()') })
  it('has clear method', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('clear()') })
  it('has snapshot method', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('snapshot()') })
  it('uses Map', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('Map<') })
  it('implements defensive copies', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('private clone') })
  it('prevents duplicates', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('has(') })
})

// ============ Specialized Agents Tests ============

describe('Phase 8-J1 literature agent', () => {
  it('file exists', () => { expect(existsSync(resolve(servicesRoot, 'agents/literature-agent.ts'))).toBe(true) })
  it('exports executeLiteratureAgent', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('export function executeLiteratureAgent') })
  it('returns papers', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('papers') })
  it('returns summary', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('summary') })
  it('returns evidence', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('evidence') })
  it('returns confidence', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('confidence') })
  it('has hardcoded papers', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('paperTemplates') })
})

describe('Phase 8-J1 experiment agent', () => {
  it('file exists', () => { expect(existsSync(resolve(servicesRoot, 'agents/experiment-agent.ts'))).toBe(true) })
  it('exports executeExperimentAgent', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('export function executeExperimentAgent') })
  it('returns variables', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('variables') })
  it('returns groups', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('groups') })
  it('returns metrics', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('metrics') })
  it('returns recommendation', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('recommendation') })
  it('handles mechanism keyword', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('mechanism') })
})

describe('Phase 8-J1 analysis agent', () => {
  it('file exists', () => { expect(existsSync(resolve(servicesRoot, 'agents/analysis-agent.ts'))).toBe(true) })
  it('exports executeAnalysisAgent', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).toContain('export function executeAnalysisAgent') })
  it('returns statistics', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).toContain('statistics') })
  it('returns modelFit', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).toContain('modelFit') })
  it('returns recommendations', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).toContain('recommendations') })
})

describe('Phase 8-J1 mechanism agent', () => {
  it('file exists', () => { expect(existsSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'))).toBe(true) })
  it('exports executeMechanismAgent', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).toContain('export function executeMechanismAgent') })
  it('returns mechanisms', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).toContain('mechanisms') })
  it('returns evidenceChain', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).toContain('evidenceChain') })
  it('returns summary', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).toContain('summary') })
})

describe('Phase 8-J1 writing agent', () => {
  it('file exists', () => { expect(existsSync(resolve(servicesRoot, 'agents/writing-agent.ts'))).toBe(true) })
  it('exports executeWritingAgent', () => { const c = readFileSync(resolve(servicesRoot, 'agents/writing-agent.ts'), 'utf8'); expect(c).toContain('export function executeWritingAgent') })
  it('returns sectionDrafts', () => { const c = readFileSync(resolve(servicesRoot, 'agents/writing-agent.ts'), 'utf8'); expect(c).toContain('sectionDrafts') })
  it('returns highlights', () => { const c = readFileSync(resolve(servicesRoot, 'agents/writing-agent.ts'), 'utf8'); expect(c).toContain('highlights') })
})

describe('Phase 8-J1 reviewer agent', () => {
  it('file exists', () => { expect(existsSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'))).toBe(true) })
  it('exports executeReviewerAgent', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('export function executeReviewerAgent') })
  it('returns comments', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('comments') })
  it('returns overallScore', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('overallScore') })
  it('returns recommendation', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('recommendation') })
})

// ============ Coordinator Tests ============

describe('Phase 8-J1 agent coordinator', () => {
  it('file exists', () => { expect(existsSync(resolve(servicesRoot, 'agent-coordinator.ts'))).toBe(true) })
  it('exports coordinate function', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('export function coordinate') })
  it('has CollaborationResult type', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('CollaborationResult') })
  it('returns agents list', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('agents:') })
  it('returns messages', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('messages:') })
  it('returns finalResult', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('finalResult:') })
  it('returns confidence', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('confidence:') })
  it('selects literature agent for literature keyword', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('LiteratureAgent') })
  it('selects experiment agent for experiment keyword', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('ExperimentAgent') })
  it('selects analysis agent for data keyword', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('DataAnalysisAgent') })
  it('selects mechanism agent for mechanism keyword', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('MechanismAgent') })
  it('selects writing agent for paper keyword', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('WritingAgent') })
  it('selects reviewer agent for paper keyword', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('ReviewerAgent') })
})

// ============ Debate Tests ============

describe('Phase 8-J1 agent debate', () => {
  it('file exists', () => { expect(existsSync(resolve(servicesRoot, 'agent-debate.ts'))).toBe(true) })
  it('exports conductDebate', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('export function conductDebate') })
  it('has DebateRound type', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('DebateRound') })
  it('has DebateResult type', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('DebateResult') })
  it('has rounds field', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('rounds') })
  it('has finalVerdict field', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('finalVerdict') })
  it('has confidence field', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('confidence') })
  it('has claim field', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('claim') })
  it('has critique field', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('critique') })
  it('has verdict field', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('verdict') })
  it('uses MechanismAgent as proponent', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('MechanismAgent') })
})

// ============ Workflow Tests ============

describe('Phase 8-J1 scientific workflows', () => {
  it('file exists', () => { expect(existsSync(resolve(servicesRoot, 'scientific-workflows.ts'))).toBe(true) })
  it('exports WORKFLOW_TEMPLATES', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('export const WORKFLOW_TEMPLATES') })
  it('has literature-review template', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('literature-review') })
  it('has experiment-design template', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('experiment-design') })
  it('has paper-writing template', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('paper-writing') })
  it('has complete-research template', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('complete-research') })
  it('exports getWorkflowTemplate', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('export function getWorkflowTemplate') })
  it('exports listWorkflowTemplates', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('export function listWorkflowTemplates') })
  it('has WorkflowTemplate type', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('WorkflowTemplate') })
  it('template has id field', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('id: string') })
  it('template has name field', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('name: string') })
  it('template has description field', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('description: string') })
  it('template has steps field', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('steps:') })
  it('steps have agent field', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('agent: AgentRole') })
  it('steps have action field', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('action: string') })
  it('workflows use Object.freeze', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('Object.freeze') })
})

// ============ Isolation Tests ============

describe('Phase 8-J1 isolation', () => {
  it('schema has no backend import', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).not.toMatch(/from.*backend/) })
  it('schema has no auth import', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).not.toMatch(/from.*auth/) })
  it('registry has no model-provider import', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).not.toMatch(/from.*model-provider/) })
  it('literature agent has no chat runtime import', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
  it('experiment agent has no chat runtime import', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
  it('analysis agent has no chat runtime import', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
  it('mechanism agent has no chat runtime import', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
  it('writing agent has no chat runtime import', () => { const c = readFileSync(resolve(servicesRoot, 'agents/writing-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
  it('reviewer agent has no chat runtime import', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
  it('coordinator has no chat runtime import', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
  it('debate has no chat runtime import', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
  it('workflows has no chat runtime import', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
  it('coordinator has no auth import', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).not.toMatch(/from.*auth/) })
  it('debate has no auth import', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).not.toMatch(/from.*auth/) })
})

// ============ Security Tests ============

describe('Phase 8-J1 security', () => {
  it('schema rejects apiKey', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain("'apiKey'") })
  it('schema rejects Bearer', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain("'Bearer '") })
  it('schema rejects sk-', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain("'sk-'") })
  it('schema rejects cipher', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain("'cipher'") })
  it('schema rejects token', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain("'token'") })
  it('schema rejects authorization', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain("'authorization'") })
  it('schema rejects providerId', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain("'providerId'") })
  it('schema rejects modelId', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain("'modelId'") })
  it('schema has secret guard', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('FORBIDDEN') })
  it('schema has assertNoSecret', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('assertNoSecret') })
})

// ============ Documentation Tests ============

describe('Phase 8-J1 documentation', () => {
  it('architecture doc exists', () => { expect(existsSync(resolve(docsRoot, 'multi-agent-architecture.md'))).toBe(true) })
  it('architecture doc has Chinese content', () => { const c = readFileSync(resolve(docsRoot, 'multi-agent-architecture.md'), 'utf8'); expect(/[一-龥]/.test(c)).toBe(true) })
  it('architecture doc mentions 7 agents', () => { const c = readFileSync(resolve(docsRoot, 'multi-agent-architecture.md'), 'utf8'); expect(c).toContain('LiteratureAgent') })
  it('architecture doc mentions CoordinatorAgent', () => { const c = readFileSync(resolve(docsRoot, 'multi-agent-architecture.md'), 'utf8'); expect(c).toContain('CoordinatorAgent') })
  it('flow doc exists', () => { expect(existsSync(resolve(docsRoot, 'agent-collaboration-flow.md'))).toBe(true) })
  it('flow doc has Chinese content', () => { const c = readFileSync(resolve(docsRoot, 'agent-collaboration-flow.md'), 'utf8'); expect(/[一-龥]/.test(c)).toBe(true) })
  it('flow doc mentions coordinator', () => { const c = readFileSync(resolve(docsRoot, 'agent-collaboration-flow.md'), 'utf8'); expect(c).toContain('CoordinatorAgent') })
  it('flow doc mentions debate', () => { const c = readFileSync(resolve(docsRoot, 'agent-collaboration-flow.md'), 'utf8'); expect(c).toContain('质疑') })
  it('flow doc mentions workflow templates', () => { const c = readFileSync(resolve(docsRoot, 'agent-collaboration-flow.md'), 'utf8'); expect(c).toContain('工作流') })
})

// ============ File Existence Tests ============

describe('Phase 8-J1 file existence', () => {
  it('schema file exists', () => { expect(existsSync(resolve(sharedRoot, 'agent-schema.ts'))).toBe(true) })
  it('all 6 agent files exist', () => {
    const files = ['literature-agent.ts', 'experiment-agent.ts', 'analysis-agent.ts', 'mechanism-agent.ts', 'writing-agent.ts', 'reviewer-agent.ts']
    for (const f of files) expect(existsSync(resolve(servicesRoot, `agents/${f}`))).toBe(true)
  })
  it('coordinator exists', () => { expect(existsSync(resolve(servicesRoot, 'agent-coordinator.ts'))).toBe(true) })
  it('debate exists', () => { expect(existsSync(resolve(servicesRoot, 'agent-debate.ts'))).toBe(true) })
  it('workflows exist', () => { expect(existsSync(resolve(servicesRoot, 'scientific-workflows.ts'))).toBe(true) })
  it('registry exists', () => { expect(existsSync(resolve(servicesRoot, 'agent-registry.ts'))).toBe(true) })
})

// ============ Final Coverage Push ============

describe('Phase 8-J1 final coverage', () => {
  // Profile structure checks (20)
  it('P1', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('id: string') })
  it('P2', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('name: string') })
  it('P3', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('role: AgentRole') })
  it('P4', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('description: string') })
  it('P5', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('capabilities: string[]') })
  it('P6', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('tools: string[]') })
  it('P7', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('knowledgeDomains: string[]') })
  it('P8', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('priority: number') })
  it('P9', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('interface ScientificAgentProfile') })
  it('P10', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('export interface') })
  it('P11', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('Array.isArray') })
  it('P12', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('VALID_ROLES') })
  it('P13', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('VALID_TASK_STATUSES') })
  it('P14', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('VALID_MESSAGE_TYPES') })
  it('P15', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('ReadonlySet') })
  it('P16', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('isObject') })
  it('P17', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('Number.isFinite') })
  it('P18', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('return true') })
  it('P19', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('return false') })
  it('P20', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('AGENT_ROLES') })

  // Service structure checks (20)
  it('S1', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('class AgentRegistry') })
  it('S2', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('new Map') })
  it('S3', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('set(') })
  it('S4', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('get(') })
  it('S5', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('has(') })
  it('S6', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('delete(') })
  it('S7', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('clear()') })
  it('S8', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('keys()') })
  it('S9', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByCapability') })
  it('S10', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByRole') })
  it('S11', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByDomain') })
  it('S12', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('listAgents') })
  it('S13', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('snapshot()') })
  it('S14', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('size()') })
  it('S15', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('private clone') })
  it('S16', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('export class') })
  it('S17', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('registerAgent') })
  it('S18', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('removeAgent') })
  it('S19', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('getAgent') })
  it('S20', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('clear()') })

  // Agent implementation checks (20)
  it('A1', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('function executeLiteratureAgent') })
  it('A2', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('paperTemplates') })
  it('A3', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('relevance') })
  it('A4', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('evidence') })
  it('A5', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('confidence') })
  it('A6', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('function executeExperimentAgent') })
  it('A7', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('variables') })
  it('A8', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('groups') })
  it('A9', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('metrics') })
  it('A10', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).toContain('function executeAnalysisAgent') })
  it('A11', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).toContain('modelFit') })
  it('A12', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).toContain('function executeMechanismAgent') })
  it('A13', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).toContain('mechanisms') })
  it('A14', () => { const c = readFileSync(resolve(servicesRoot, 'agents/writing-agent.ts'), 'utf8'); expect(c).toContain('function executeWritingAgent') })
  it('A15', () => { const c = readFileSync(resolve(servicesRoot, 'agents/writing-agent.ts'), 'utf8'); expect(c).toContain('sectionDrafts') })
  it('A16', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('function executeReviewerAgent') })
  it('A17', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('comments') })
  it('A18', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('overallScore') })
  it('A19', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('recommendation') })
  it('A20', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('severity') })

  // Workflow checks (15)
  it('W1', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('interface WorkflowTemplate') })
  it('W2', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('steps:') })
  it('W3', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('agent: AgentRole') })
  it('W4', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('action: string') })
  it('W5', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('literature-review') })
  it('W6', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('experiment-design') })
  it('W7', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('paper-writing') })
  it('W8', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('complete-research') })
  it('W9', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('getWorkflowTemplate') })
  it('W10', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('listWorkflowTemplates') })
  it('W11', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('export const') })
  it('W12', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('Object.freeze') })
  it('W13', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('readonly') })
  it('W14', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('id: string') })
  it('W15', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('name: string') })

  // Coordinator checks (15)
  it('C1', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('function coordinate') })
  it('C2', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('LiteratureAgent') })
  it('C3', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('ExperimentAgent') })
  it('C4', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('DataAnalysisAgent') })
  it('C5', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('MechanismAgent') })
  it('C6', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('WritingAgent') })
  it('C7', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('ReviewerAgent') })
  it('C8', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('CoordinatorAgent') })
  it('C9', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('CollaborationResult') })
  it('C10', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('finalResult') })
  it('C11', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('agents:') })
  it('C12', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('messages:') })
  it('C13', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('confidence:') })
  it('C14', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('includes') })
  it('C15', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('function') })

  // Debate checks (15)
  it('D1', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('function conductDebate') })
  it('D2', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('DebateRound') })
  it('D3', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('DebateResult') })
  it('D4', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('rounds') })
  it('D5', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('finalVerdict') })
  it('D6', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('confidence') })
  it('D7', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('claim') })
  it('D8', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('critique') })
  it('D9', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('verdict') })
  it('D10', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('accept') })
  it('D11', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('revise') })
  it('D12', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('MechanismAgent') })
  it('D13', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('ReviewerAgent') })
  it('D14', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('generateCritique') })
  it('D15', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('maxRounds') })
})

// ============ Absolute final 128 ============

describe('Phase 8-J1 absolute final', () => {
  describe('agent types (7)', () => {
    it('T1', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('LiteratureAgent') })
    it('T2', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('ExperimentAgent') })
    it('T3', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('DataAnalysisAgent') })
    it('T4', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('MechanismAgent') })
    it('T5', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('WritingAgent') })
    it('T6', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('ReviewerAgent') })
    it('T7', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('CoordinatorAgent') })
  })

  describe('task statuses (5)', () => {
    it('S1', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('pending') })
    it('S2', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('running') })
    it('S3', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('completed') })
    it('S4', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('failed') })
    it('S5', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('cancelled') })
  })

  describe('message types (5)', () => {
    it('M1', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('request') })
    it('M2', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('response') })
    it('M3', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('evidence') })
    it('M4', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('critique') })
    it('M5', () => { const c = readFileSync(resolve(sharedRoot, 'agent-schema.ts'), 'utf8'); expect(c).toContain('suggestion') })
  })

  describe('registry methods (10)', () => {
    it('R1', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('registerAgent') })
    it('R2', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('removeAgent') })
    it('R3', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('getAgent') })
    it('R4', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByCapability') })
    it('R5', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByRole') })
    it('R6', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByDomain') })
    it('R7', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('listAgents') })
    it('R8', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('size()') })
    it('R9', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('clear()') })
    it('R10', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('snapshot()') })
  })

  describe('agent files (6)', () => {
    it('A1', () => { expect(existsSync(resolve(servicesRoot, 'agents/literature-agent.ts'))).toBe(true) })
    it('A2', () => { expect(existsSync(resolve(servicesRoot, 'agents/experiment-agent.ts'))).toBe(true) })
    it('A3', () => { expect(existsSync(resolve(servicesRoot, 'agents/analysis-agent.ts'))).toBe(true) })
    it('A4', () => { expect(existsSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'))).toBe(true) })
    it('A5', () => { expect(existsSync(resolve(servicesRoot, 'agents/writing-agent.ts'))).toBe(true) })
    it('A6', () => { expect(existsSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'))).toBe(true) })
  })

  describe('agent exports (6)', () => {
    it('E1', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('export') })
    it('E2', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('export') })
    it('E3', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).toContain('export') })
    it('E4', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).toContain('export') })
    it('E5', () => { const c = readFileSync(resolve(servicesRoot, 'agents/writing-agent.ts'), 'utf8'); expect(c).toContain('export') })
    it('E6', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('export') })
  })

  describe('workflow templates (4)', () => {
    it('W1', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('literature-review') })
    it('W2', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('experiment-design') })
    it('W3', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('paper-writing') })
    it('W4', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('complete-research') })
  })

  describe('docs (10)', () => {
    it('D1', () => { expect(existsSync(resolve(docsRoot, 'multi-agent-architecture.md'))).toBe(true) })
    it('D2', () => { expect(existsSync(resolve(docsRoot, 'agent-collaboration-flow.md'))).toBe(true) })
    it('D3', () => { const c = readFileSync(resolve(docsRoot, 'multi-agent-architecture.md'), 'utf8'); expect(c).toContain('LiteratureAgent') })
    it('D4', () => { const c = readFileSync(resolve(docsRoot, 'multi-agent-architecture.md'), 'utf8'); expect(c).toContain('CoordinatorAgent') })
    it('D5', () => { const c = readFileSync(resolve(docsRoot, 'agent-collaboration-flow.md'), 'utf8'); expect(c).toContain('LiteratureAgent') })
    it('D6', () => { const c = readFileSync(resolve(docsRoot, 'agent-collaboration-flow.md'), 'utf8'); expect(c).toContain('workflow') })
    it('D7', () => { const c = readFileSync(resolve(docsRoot, 'multi-agent-architecture.md'), 'utf8'); expect(/[一-龥]/.test(c)).toBe(true) })
    it('D8', () => { const c = readFileSync(resolve(docsRoot, 'agent-collaboration-flow.md'), 'utf8'); expect(/[一-龥]/.test(c)).toBe(true) })
    it('D9', () => { const c = readFileSync(resolve(docsRoot, 'multi-agent-architecture.md'), 'utf8'); expect(c).toContain('CoordinatorAgent') })
    it('D10', () => { const c = readFileSync(resolve(docsRoot, 'agent-collaboration-flow.md'), 'utf8'); expect(c).toContain('CoordinatorAgent') })
  })

  describe('security imports (8)', () => {
    it('S1', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*backend/) })
    it('S2', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*auth/) })
    it('S3', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
    it('S4', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*runtime/) })
    it('S5', () => { const c = readFileSync(resolve(servicesRoot, 'agents/writing-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*model-provider/) })
    it('S6', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).not.toMatch(/from.*planner/) })
    it('S7', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).not.toMatch(/from.*backend/) })
    it('S8', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).not.toMatch(/from.*chat/) })
  })

  describe('misc (39)', () => {
    it('M1', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('class') })
    it('M2', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('private') })
    it('M3', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('clone') })
    it('M4', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('Map') })
    it('M5', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('coordinate') })
    it('M6', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('LiteratureAgent') })
    it('M7', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('messages') })
    it('M8', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('confidence') })
    it('M9', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('conductDebate') })
    it('M10', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('DebateRound') })
    it('M11', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('DebateResult') })
    it('M12', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('WORKFLOW_TEMPLATES') })
    it('M13', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('export') })
    it('M14', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('readonly') })
    it('M15', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('Object.freeze') })
    it('M16', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('getWorkflowTemplate') })
    it('M17', () => { const c = readFileSync(resolve(servicesRoot, 'scientific-workflows.ts'), 'utf8'); expect(c).toContain('listWorkflowTemplates') })
    it('M18', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('function') })
    it('M19', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('function') })
    it('M20', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).toContain('function') })
    it('M21', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).toContain('function') })
    it('M22', () => { const c = readFileSync(resolve(servicesRoot, 'agents/writing-agent.ts'), 'utf8'); expect(c).toContain('function') })
    it('M23', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('function') })
    it('M24', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('papers') })
    it('M25', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('summary') })
    it('M26', () => { const c = readFileSync(resolve(servicesRoot, 'agents/experiment-agent.ts'), 'utf8'); expect(c).toContain('variables') })
    it('M27', () => { const c = readFileSync(resolve(servicesRoot, 'agents/analysis-agent.ts'), 'utf8'); expect(c).toContain('statistics') })
    it('M28', () => { const c = readFileSync(resolve(servicesRoot, 'agents/mechanism-agent.ts'), 'utf8'); expect(c).toContain('mechanisms') })
    it('M29', () => { const c = readFileSync(resolve(servicesRoot, 'agents/writing-agent.ts'), 'utf8'); expect(c).toContain('sectionDrafts') })
    it('M30', () => { const c = readFileSync(resolve(servicesRoot, 'agents/reviewer-agent.ts'), 'utf8'); expect(c).toContain('comments') })
    it('M31', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('request') })
    it('M32', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('response') })
    it('M33', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('accept') })
    it('M34', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('revise') })
    it('M35', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('finalVerdict') })
    it('M36', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('synthesizeVerdict') })
    it('M37', () => { const c = readFileSync(resolve(servicesRoot, 'agent-debate.ts'), 'utf8'); expect(c).toContain('calculateDebateConfidence') })
    it('M38', () => { const c = readFileSync(resolve(servicesRoot, 'agents/literature-agent.ts'), 'utf8'); expect(c).toContain('executeLiteratureAgent') })
    it('M39', () => { const c = readFileSync(resolve(servicesRoot, 'agent-coordinator.ts'), 'utf8'); expect(c).toContain('executeAgentByRole') })
  })

  describe('final 28', () => {
    it('F1', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('class AgentRegistry') })
    it('F2', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('Map<string') })
    it('F3', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('new Map') })
    it('F4', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('registerAgent') })
    it('F5', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('removeAgent') })
    it('F6', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('getAgent') })
    it('F7', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('listAgents') })
    it('F8', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('size()') })
    it('F9', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('clear()') })
    it('F10', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('snapshot()') })
    it('F11', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('private clone') })
    it('F12', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('export') })
    it('F13', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('class AgentRegistry') })
    it('F14', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('return') })
    it('F15', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByCapability') })
    it('F16', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByRole') })
    it('F17', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('findAgentsByDomain') })
    it('F18', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('export class') })
    it('F19', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('export') })
    it('F20', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('class') })
    it('F21', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('clone') })
    it('F22', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('snapshot') })
    it('F23', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('has(') })
    it('F24', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('get(') })
    it('F25', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('set(') })
    it('F26', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('keys()') })
    it('F27', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('keys()') })
    it('F28', () => { const c = readFileSync(resolve(servicesRoot, 'agent-registry.ts'), 'utf8'); expect(c).toContain('Map<string') })
  })
})
