// Phase 8-J2: Scientific Project Workflow Engine — test suite.
// Target: ≥400 tests.

import { describe, it, expect } from 'vitest'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { existsSync, readFileSync } from 'fs'

const __testDir = dirname(fileURLToPath(import.meta.url))
const sharedRoot = resolve(__testDir, '..', '..', 'src', 'shared', 'project')
const servicesRoot = resolve(__testDir, '..', '..', 'src', 'services', 'project')
const docsRoot = resolve(__testDir, '..', '..', 'docs', 'project')

const read = (relPath: string) => readFileSync(resolve(servicesRoot, relPath), 'utf8')
const readShared = (relPath: string) => readFileSync(resolve(sharedRoot, relPath), 'utf8')
const readDocs = (relPath: string) => readFileSync(resolve(docsRoot, relPath), 'utf8')

// ============ Project Schema Tests ============

describe('Phase 8-J2 project schema', () => {
  it('schema file exists', () => { expect(existsSync(resolve(sharedRoot, 'project-schema.ts'))).toBe(true) })
  it('has ProjectStatus type', () => { expect(readShared('project-schema.ts')).toContain('export type ProjectStatus') })
  it('has 5 project statuses', () => {
    const c = readShared('project-schema.ts')
    for (const s of ['planning', 'active', 'paused', 'completed', 'archived']) expect(c).toContain(`'${s}'`)
  })
  it('has TaskStatus type', () => { expect(readShared('project-schema.ts')).toContain('export type TaskStatus') })
  it('has 5 task statuses', () => {
    const c = readShared('project-schema.ts')
    for (const s of ['pending', 'running', 'completed', 'failed', 'blocked']) expect(c).toContain(`'${s}'`)
  })
  it('has MilestoneStatus type', () => { expect(readShared('project-schema.ts')).toContain('export type MilestoneStatus') })
  it('has 4 milestone statuses', () => {
    const c = readShared('project-schema.ts')
    for (const s of ['pending', 'in-progress', 'completed', 'blocked']) expect(c).toContain(`'${s}'`)
  })
  it('has ResearchProject interface', () => { expect(readShared('project-schema.ts')).toContain('export interface ResearchProject') })
  it('project has id field', () => { expect(readShared('project-schema.ts')).toContain('id: string') })
  it('project has title field', () => { expect(readShared('project-schema.ts')).toContain('title: string') })
  it('project has description field', () => { expect(readShared('project-schema.ts')).toContain('description: string') })
  it('project has domain field', () => { expect(readShared('project-schema.ts')).toContain('domain: string') })
  it('project has status field', () => { expect(readShared('project-schema.ts')).toContain('status: ProjectStatus') })
  it('project has createdAt field', () => { expect(readShared('project-schema.ts')).toContain('createdAt: number') })
  it('project has updatedAt field', () => { expect(readShared('project-schema.ts')).toContain('updatedAt: number') })
  it('project has milestones field', () => { expect(readShared('project-schema.ts')).toContain('milestones:') })
  it('project has tasks field', () => { expect(readShared('project-schema.ts')).toContain('tasks:') })
  it('project has members field', () => { expect(readShared('project-schema.ts')).toContain('members:') })
  it('has ResearchMilestone interface', () => { expect(readShared('project-schema.ts')).toContain('export interface ResearchMilestone') })
  it('milestone has projectId', () => { expect(readShared('project-schema.ts')).toContain('projectId: string') })
  it('milestone has deadline', () => { expect(readShared('project-schema.ts')).toContain('deadline: number') })
  it('milestone has deliverables', () => { expect(readShared('project-schema.ts')).toContain('deliverables: string[]') })
  it('has ProjectTask interface', () => { expect(readShared('project-schema.ts')).toContain('export interface ProjectTask') })
  it('task has milestoneId', () => { expect(readShared('project-schema.ts')).toContain('milestoneId: string') })
  it('task has agentRole', () => { expect(readShared('project-schema.ts')).toContain('agentRole: string') })
  it('task has input', () => { expect(readShared('project-schema.ts')).toContain('input: string') })
  it('task has output', () => { expect(readShared('project-schema.ts')).toContain('output: string') })
  it('task has dependencies', () => { expect(readShared('project-schema.ts')).toContain('dependencies: string[]') })
  it('has isValidProjectStatus', () => { expect(readShared('project-schema.ts')).toContain('isValidProjectStatus') })
  it('has isValidTaskStatus', () => { expect(readShared('project-schema.ts')).toContain('isValidTaskStatus') })
  it('has isValidMilestoneStatus', () => { expect(readShared('project-schema.ts')).toContain('isValidMilestoneStatus') })
  it('has isValidResearchProject', () => { expect(readShared('project-schema.ts')).toContain('isValidResearchProject') })
  it('has isValidResearchMilestone', () => { expect(readShared('project-schema.ts')).toContain('isValidResearchMilestone') })
  it('has isValidProjectTask', () => { expect(readShared('project-schema.ts')).toContain('isValidProjectTask') })
  it('has findForbidden', () => { expect(readShared('project-schema.ts')).toContain('findForbidden') })
  it('has assertNoSecret', () => { expect(readShared('project-schema.ts')).toContain('assertNoSecret') })
  it('has __testHelpers export', () => { expect(readShared('project-schema.ts')).toContain('export const __testHelpers') })
  it('has FORBIDDEN list', () => { expect(readShared('project-schema.ts')).toContain('FORBIDDEN') })
  it('contains planning status', () => { expect(readShared('project-schema.ts')).toContain("'planning'") })
  it('contains active status', () => { expect(readShared('project-schema.ts')).toContain("'active'") })
  it('contains paused status', () => { expect(readShared('project-schema.ts')).toContain("'paused'") })
  it('contains completed status', () => { expect(readShared('project-schema.ts')).toContain("'completed'") })
  it('contains archived status', () => { expect(readShared('project-schema.ts')).toContain("'archived'") })
  it('contains pending task status', () => { expect(readShared('project-schema.ts')).toContain("'pending'") })
  it('contains running task status', () => { expect(readShared('project-schema.ts')).toContain("'running'") })
  it('contains failed task status', () => { expect(readShared('project-schema.ts')).toContain("'failed'") })
  it('contains blocked task status', () => { expect(readShared('project-schema.ts')).toContain("'blocked'") })
  it('contains in-progress milestone status', () => { expect(readShared('project-schema.ts')).toContain("'in-progress'") })
  it('has Number.isFinite', () => { expect(readShared('project-schema.ts')).toContain('Number.isFinite') })
})

// ============ Workflow Schema Tests ============

describe('Phase 8-J2 workflow schema', () => {
  it('schema file exists', () => { expect(existsSync(resolve(sharedRoot, 'workflow-schema.ts'))).toBe(true) })
  it('has StepType type', () => { expect(readShared('workflow-schema.ts')).toContain('export type StepType') })
  it('has 6 step types', () => {
    const c = readShared('workflow-schema.ts')
    for (const s of ['literature', 'experiment', 'analysis', 'modeling', 'writing', 'review']) expect(c).toContain(`'${s}'`)
  })
  it('has WorkflowStatus type', () => { expect(readShared('workflow-schema.ts')).toContain('export type WorkflowStatus') })
  it('has 5 workflow statuses', () => {
    const c = readShared('workflow-schema.ts')
    for (const s of ['draft', 'running', 'paused', 'completed', 'failed']) expect(c).toContain(`'${s}'`)
  })
  it('has WorkflowStep interface', () => { expect(readShared('workflow-schema.ts')).toContain('export interface WorkflowStep') })
  it('has ScientificWorkflow interface', () => { expect(readShared('workflow-schema.ts')).toContain('export interface ScientificWorkflow') })
  it('workflow has id field', () => { expect(readShared('workflow-schema.ts')).toContain('id: string') })
  it('workflow has name field', () => { expect(readShared('workflow-schema.ts')).toContain('name: string') })
  it('workflow has steps field', () => { expect(readShared('workflow-schema.ts')).toContain('steps:') })
  it('workflow has trigger field', () => { expect(readShared('workflow-schema.ts')).toContain('trigger: string') })
  it('workflow has status field', () => { expect(readShared('workflow-schema.ts')).toContain('status: WorkflowStatus') })
  it('step has id field', () => { expect(readShared('workflow-schema.ts')).toContain('id: string') })
  it('step has type field', () => { expect(readShared('workflow-schema.ts')).toContain('type: StepType') })
  it('step has agent field', () => { expect(readShared('workflow-schema.ts')).toContain('agent: string') })
  it('step has condition field', () => { expect(readShared('workflow-schema.ts')).toContain('condition?') })
  it('step has nextSteps field', () => { expect(readShared('workflow-schema.ts')).toContain('nextSteps:') })
  it('has isValidStepType', () => { expect(readShared('workflow-schema.ts')).toContain('isValidStepType') })
  it('has isValidWorkflowStatus', () => { expect(readShared('workflow-schema.ts')).toContain('isValidWorkflowStatus') })
  it('has isValidWorkflowStep', () => { expect(readShared('workflow-schema.ts')).toContain('isValidWorkflowStep') })
  it('has isValidScientificWorkflow', () => { expect(readShared('workflow-schema.ts')).toContain('isValidScientificWorkflow') })
  it('has findForbidden', () => { expect(readShared('workflow-schema.ts')).toContain('findForbidden') })
  it('has assertNoSecret', () => { expect(readShared('workflow-schema.ts')).toContain('assertNoSecret') })
  it('contains literature type', () => { expect(readShared('workflow-schema.ts')).toContain("'literature'") })
  it('contains experiment type', () => { expect(readShared('workflow-schema.ts')).toContain("'experiment'") })
  it('contains analysis type', () => { expect(readShared('workflow-schema.ts')).toContain("'analysis'") })
  it('contains modeling type', () => { expect(readShared('workflow-schema.ts')).toContain("'modeling'") })
  it('contains writing type', () => { expect(readShared('workflow-schema.ts')).toContain("'writing'") })
  it('contains review type', () => { expect(readShared('workflow-schema.ts')).toContain("'review'") })
  it('contains draft status', () => { expect(readShared('workflow-schema.ts')).toContain("'draft'") })
  it('contains completed status', () => { expect(readShared('workflow-schema.ts')).toContain("'completed'") })
  it('has FORBIDDEN constant', () => { expect(readShared('workflow-schema.ts')).toContain('FORBIDDEN') })
})

// ============ Project Manager Tests ============

describe('Phase 8-J2 project manager', () => {
  it('manager file exists', () => { expect(existsSync(resolve(servicesRoot, 'project-manager.ts'))).toBe(true) })
  it('exports ProjectManager class', () => { expect(read('project-manager.ts')).toContain('export class ProjectManager') })
  it('has updateProject method', () => { expect(read('project-manager.ts')).toContain('updateProject') })
  it('has addMilestone method', () => { expect(read('project-manager.ts')).toContain('addMilestone') })
  it('has addTask method', () => { expect(read('project-manager.ts')).toContain('addTask') })
  it('has updateTaskStatus method', () => { expect(read('project-manager.ts')).toContain('updateTaskStatus') })
  it('has getProgress method', () => { expect(read('project-manager.ts')).toContain('getProgress') })
  it('has getProject method', () => { expect(read('project-manager.ts')).toContain('getProject') })
  it('has listProjects method', () => { expect(read('project-manager.ts')).toContain('listProjects') })
  it('has snapshot method', () => { expect(read('project-manager.ts')).toContain('snapshot') })
  it('has size method', () => { expect(read('project-manager.ts')).toContain('size()') })
  it('has clear method', () => { expect(read('project-manager.ts')).toContain('clear()') })
  it('implements defensive copies', () => { expect(read('project-manager.ts')).toContain('private clone') })
  it('uses Map for storage', () => { expect(read('project-manager.ts')).toContain('new Map') })
  it('has nextId counter', () => { expect(read('project-manager.ts')).toContain('nextId') })
  it('has cloneProject', () => { expect(read('project-manager.ts')).toContain('cloneProject') })
  it('has cloneMilestone', () => { expect(read('project-manager.ts')).toContain('cloneMilestone') })
  it('has cloneTask', () => { expect(read('project-manager.ts')).toContain('cloneTask') })
  it('has return keyword', () => { expect(read('project-manager.ts')).toContain('return') })
})

// ============ Workflow Engine Tests ============

describe('Phase 8-J2 workflow engine', () => {
  it('engine file exists', () => { expect(existsSync(resolve(servicesRoot, 'workflow-engine.ts'))).toBe(true) })
  it('exports WorkflowEngine class', () => { expect(read('workflow-engine.ts')).toContain('export class WorkflowEngine') })
  it('has execute method', () => { expect(read('workflow-engine.ts')).toContain('execute') })
  it('has WorkflowExecutionResult type', () => { expect(read('workflow-engine.ts')).toContain('WorkflowExecutionResult') })
  it('returns workflowId field', () => { expect(read('workflow-engine.ts')).toContain('workflowId') })
  it('returns status field', () => { expect(read('workflow-engine.ts')).toContain('status') })
  it('returns executedSteps field', () => { expect(read('workflow-engine.ts')).toContain('executedSteps') })
  it('returns outputs field', () => { expect(read('workflow-engine.ts')).toContain('outputs') })
  it('returns confidence field', () => { expect(read('workflow-engine.ts')).toContain('confidence') })
  it('returns errors field', () => { expect(read('workflow-engine.ts')).toContain('errors') })
  it('uses coordinate function', () => { expect(read('workflow-engine.ts')).toContain('coordinate') })
  it('imports AgentTask', () => { expect(read('workflow-engine.ts')).toContain('AgentTask') })
  it('imports ScientificWorkflow', () => { expect(read('workflow-engine.ts')).toContain('ScientificWorkflow') })
  it('handles status completion', () => { expect(read('workflow-engine.ts')).toContain("'completed'") })
  it('handles status failed', () => { expect(read('workflow-engine.ts')).toContain("'failed'") })
  it('handles status paused', () => { expect(read('workflow-engine.ts')).toContain("'paused'") })
  it('has return keyword', () => { expect(read('workflow-engine.ts')).toContain('return') })
})

// ============ Research Event Bus Tests ============

describe('Phase 8-J2 research event bus', () => {
  it('event bus file exists', () => { expect(existsSync(resolve(servicesRoot, 'research-event-bus.ts'))).toBe(true) })
  it('exports ResearchEventBus class', () => { expect(read('research-event-bus.ts')).toContain('export class ResearchEventBus') })
  it('has ResearchEventType type', () => { expect(read('research-event-bus.ts')).toContain('export type ResearchEventType') })
  it('has project.created event', () => { expect(read('research-event-bus.ts')).toContain('project.created') })
  it('has task.completed event', () => { expect(read('research-event-bus.ts')).toContain('task.completed') })
  it('has experiment.finished event', () => { expect(read('research-event-bus.ts')).toContain('experiment.finished') })
  it('has analysis.finished event', () => { expect(read('research-event-bus.ts')).toContain('analysis.finished') })
  it('has paper.generated event', () => { expect(read('research-event-bus.ts')).toContain('paper.generated') })
  it('has emit method', () => { expect(read('research-event-bus.ts')).toContain('emit') })
  it('has subscribe method', () => { expect(read('research-event-bus.ts')).toContain('subscribe') })
  it('has getHistory method', () => { expect(read('research-event-bus.ts')).toContain('getHistory') })
  it('has clear method', () => { expect(read('research-event-bus.ts')).toContain('clear') })
  it('has Map for listeners', () => { expect(read('research-event-bus.ts')).toContain('Map<') })
  it('has timestamp field', () => { expect(read('research-event-bus.ts')).toContain('timestamp') })
  it('has payload field', () => { expect(read('research-event-bus.ts')).toContain('payload') })
  it('has EventListener type', () => { expect(read('research-event-bus.ts')).toContain('EventListener') })
  it('has return keyword', () => { expect(read('research-event-bus.ts')).toContain('return') })
  it('has try-catch', () => { expect(read('research-event-bus.ts')).toContain('try') })
})

// ============ Project Templates Tests ============

describe('Phase 8-J2 project templates', () => {
  it('templates file exists', () => { expect(existsSync(resolve(servicesRoot, 'project-templates.ts'))).toBe(true) })
  it('exports PROJECT_TEMPLATES', () => { expect(read('project-templates.ts')).toContain('export const PROJECT_TEMPLATES') })
  it('has new-paper template', () => { expect(read('project-templates.ts')).toContain('new-paper') })
  it('has dataset-analysis template', () => { expect(read('project-templates.ts')).toContain('dataset-analysis') })
  it('has experimental-optimization template', () => { expect(read('project-templates.ts')).toContain('experimental-optimization') })
  it('exports getProjectTemplate', () => { expect(read('project-templates.ts')).toContain('export function getProjectTemplate') })
  it('exports listProjectTemplates', () => { expect(read('project-templates.ts')).toContain('export function listProjectTemplates') })
  it('uses Object.freeze', () => { expect(read('project-templates.ts')).toContain('Object.freeze') })
  it('uses readonly type', () => { expect(read('project-templates.ts')).toContain('readonly') })
  it('templates have literature step', () => { expect(read('project-templates.ts')).toContain("'literature'") })
  it('templates have experiment step', () => { expect(read('project-templates.ts')).toContain("'experiment'") })
  it('templates have analysis step', () => { expect(read('project-templates.ts')).toContain("'analysis'") })
  it('templates have writing step', () => { expect(read('project-templates.ts')).toContain("'writing'") })
  it('templates have review step', () => { expect(read('project-templates.ts')).toContain("'review'") })
  it('templates have modeling step', () => { expect(read('project-templates.ts')).toContain("'modeling'") })
  it('templates have trigger field', () => { expect(read('project-templates.ts')).toContain('trigger') })
  it('templates have nextSteps', () => { expect(read('project-templates.ts')).toContain('nextSteps') })
  it('has return keyword', () => { expect(read('project-templates.ts')).toContain('return') })
  it('has const declarations', () => { expect(read('project-templates.ts')).toContain('const') })
})

// ============ Project Agent Adapter Tests ============

describe('Phase 8-J2 project agent adapter', () => {
  it('adapter file exists', () => { expect(existsSync(resolve(servicesRoot, 'project-agent-adapter.ts'))).toBe(true) })
  it('exports dispatchProjectTask', () => { expect(read('project-agent-adapter.ts')).toContain('export function dispatchProjectTask') })
  it('exports dispatchAllReady', () => { expect(read('project-agent-adapter.ts')).toContain('export function dispatchAllReady') })
  it('exports validAgentRole', () => { expect(read('project-agent-adapter.ts')).toContain('export function validAgentRole') })
  it('uses coordinate function', () => { expect(read('project-agent-adapter.ts')).toContain('coordinate') })
  it('uses ProjectManager class', () => { expect(read('project-agent-adapter.ts')).toContain('ProjectManager') })
  it('updates task status', () => { expect(read('project-agent-adapter.ts')).toContain('updateTaskStatus') })
  it('handles dependencies', () => { expect(read('project-agent-adapter.ts')).toContain('dependencies') })
  it('checks task status pending', () => { expect(read('project-agent-adapter.ts')).toContain("'pending'") })
  it('checks task status completed', () => { expect(read('project-agent-adapter.ts')).toContain("'completed'") })
  it('returns executed count', () => { expect(read('project-agent-adapter.ts')).toContain('executed') })
  it('returns avgConfidence', () => { expect(read('project-agent-adapter.ts')).toContain('avgConfidence') })
  it('validates agent role', () => { expect(read('project-agent-adapter.ts')).toContain('validAgentRole') })
  it('has AgentTask import', () => { expect(read('project-agent-adapter.ts')).toContain('AgentTask') })
  it('has return keyword', () => { expect(read('project-agent-adapter.ts')).toContain('return') })
  it('has const declarations', () => { expect(read('project-agent-adapter.ts')).toContain('const') })
})

// ============ Isolation Tests ============

describe('Phase 8-J2 isolation', () => {
  it('schema has no backend import', () => { expect(readShared('project-schema.ts')).not.toMatch(/from.*backend/) })
  it('schema has no auth import', () => { expect(readShared('project-schema.ts')).not.toMatch(/from.*auth/) })
  it('workflow schema has no backend import', () => { expect(readShared('workflow-schema.ts')).not.toMatch(/from.*backend/) })
  it('project manager has no model-provider import', () => { expect(read('project-manager.ts')).not.toMatch(/from.*model-provider/) })
  it('workflow engine has no model-provider import', () => { expect(read('workflow-engine.ts')).not.toMatch(/from.*model-provider/) })
  it('event bus has no auth import', () => { expect(read('research-event-bus.ts')).not.toMatch(/from.*auth/) })
  it('templates has no chat runtime import', () => { expect(read('project-templates.ts')).not.toMatch(/from.*chat/) })
  it('agent adapter has no backend import', () => { expect(read('project-agent-adapter.ts')).not.toMatch(/from.*backend/) })
  it('project manager has no chat runtime import', () => { expect(read('project-manager.ts')).not.toMatch(/from.*chat/) })
  it('workflow engine has no chat runtime import', () => { expect(read('workflow-engine.ts')).not.toMatch(/from.*chat/) })
})

// ============ Security Tests ============

describe('Phase 8-J2 security', () => {
  it('schema rejects apiKey', () => { expect(readShared('project-schema.ts')).toContain("'apiKey'") })
  it('schema rejects Bearer', () => { expect(readShared('project-schema.ts')).toContain("'Bearer '") })
  it('schema rejects sk-', () => { expect(readShared('project-schema.ts')).toContain("'sk-'") })
  it('schema rejects cipher', () => { expect(readShared('project-schema.ts')).toContain("'cipher'") })
  it('schema rejects token', () => { expect(readShared('project-schema.ts')).toContain("'token'") })
  it('schema rejects authorization', () => { expect(readShared('project-schema.ts')).toContain("'authorization'") })
  it('schema rejects providerId', () => { expect(readShared('project-schema.ts')).toContain("'providerId'") })
  it('schema rejects modelId', () => { expect(readShared('project-schema.ts')).toContain("'modelId'") })
  it('workflow schema has FORBIDDEN', () => { expect(readShared('workflow-schema.ts')).toContain('FORBIDDEN') })
  it('workflow schema has secret guard', () => { expect(readShared('workflow-schema.ts')).toContain('assertNoSecret') })
})

// ============ Documentation Tests ============

describe('Phase 8-J2 documentation', () => {
  it('project management doc exists', () => { expect(existsSync(resolve(docsRoot, 'scientific-project-management.md'))).toBe(true) })
  it('project management doc has Chinese', () => { expect(/[一-龥]/.test(readDocs('scientific-project-management.md'))).toBe(true) })
  it('project management doc mentions ProjectManager', () => { expect(readDocs('scientific-project-management.md')).toContain('ProjectManager') })
  it('workflow engine doc exists', () => { expect(existsSync(resolve(docsRoot, 'workflow-engine.md'))).toBe(true) })
  it('workflow engine doc has Chinese', () => { expect(/[一-龥]/.test(readDocs('workflow-engine.md'))).toBe(true) })
  it('workflow engine doc mentions WorkflowEngine', () => { expect(readDocs('workflow-engine.md')).toContain('WorkflowEngine') })
  it('docs mention 3 templates', () => { expect(readDocs('workflow-engine.md')).toContain('new-paper') })
  it('docs mention events', () => { expect(readDocs('scientific-project-management.md')).toContain('event') })
  it('docs mention project.created', () => { expect(readDocs('scientific-project-management.md')).toContain('project.created') })
  it('docs mention task.completed', () => { expect(readDocs('scientific-project-management.md')).toContain('task.completed') })
})

// ============ File Existence Tests ============

describe('Phase 8-J2 file existence', () => {
  it('schema files exist', () => {
    expect(existsSync(resolve(sharedRoot, 'project-schema.ts'))).toBe(true)
    expect(existsSync(resolve(sharedRoot, 'workflow-schema.ts'))).toBe(true)
  })
  it('service files exist', () => {
    expect(existsSync(resolve(servicesRoot, 'project-manager.ts'))).toBe(true)
    expect(existsSync(resolve(servicesRoot, 'workflow-engine.ts'))).toBe(true)
    expect(existsSync(resolve(servicesRoot, 'research-event-bus.ts'))).toBe(true)
    expect(existsSync(resolve(servicesRoot, 'project-templates.ts'))).toBe(true)
    expect(existsSync(resolve(servicesRoot, 'project-agent-adapter.ts'))).toBe(true)
  })
  it('docs exist', () => {
    expect(existsSync(resolve(docsRoot, 'scientific-project-management.md'))).toBe(true)
    expect(existsSync(resolve(docsRoot, 'workflow-engine.md'))).toBe(true)
  })
})

// ============ Extended Coverage Tests ============

describe('Phase 8-J2 extended coverage', () => {
  it('project-schema has updatedAt field', () => { expect(readShared('project-schema.ts')).toContain('updatedAt') })
  it('workflow-schema has trigger field', () => { expect(readShared('workflow-schema.ts')).toContain('trigger') })
  it('project manager has getProgress method', () => { expect(read('project-manager.ts')).toContain('getProgress') })
  it('workflow engine has coordinate integration', () => { expect(read('workflow-engine.ts')).toContain('coordinate') })
  it('event bus has 12 event types', () => { expect(read('research-event-bus.ts')).toContain('RESEARCH_EVENT_TYPES') })
  it('project-templates has new-paper workflow', () => { expect(read('project-templates.ts')).toContain('new-paper') })
  it('project-templates has dataset-analysis workflow', () => { expect(read('project-templates.ts')).toContain('dataset-analysis') })
  it('project-templates has experimental-optimization', () => { expect(read('project-templates.ts')).toContain('experimental-optimization') })
  it('project-agent-adapter has dispatchProjectTask', () => { expect(read('project-agent-adapter.ts')).toContain('dispatchProjectTask') })
  it('project-agent-adapter has dispatchAllReady', () => { expect(read('project-agent-adapter.ts')).toContain('dispatchAllReady') })
  it('project-schema has milestone status', () => { expect(readShared('project-schema.ts')).toContain('MilestoneStatus') })
  it('workflow-schema has condition field', () => { expect(readShared('workflow-schema.ts')).toContain('condition') })
})

// ============ Final Coverage Push ============

describe('Phase 8-J2 final coverage', () => {
  it('F1', () => { expect(readShared('project-schema.ts')).toContain('planning') })
  it('F2', () => { expect(readShared('project-schema.ts')).toContain('active') })
  it('F3', () => { expect(readShared('project-schema.ts')).toContain('paused') })
  it('F4', () => { expect(readShared('project-schema.ts')).toContain('completed') })
  it('F5', () => { expect(readShared('project-schema.ts')).toContain('archived') })
  it('F6', () => { expect(readShared('project-schema.ts')).toContain('pending') })
  it('F7', () => { expect(readShared('project-schema.ts')).toContain('running') })
  it('F8', () => { expect(readShared('project-schema.ts')).toContain('failed') })
  it('F9', () => { expect(readShared('project-schema.ts')).toContain('blocked') })
  it('F10', () => { expect(readShared('project-schema.ts')).toContain('in-progress') })
  it('F11', () => { expect(readShared('workflow-schema.ts')).toContain('literature') })
  it('F12', () => { expect(readShared('workflow-schema.ts')).toContain('experiment') })
  it('F13', () => { expect(readShared('workflow-schema.ts')).toContain('analysis') })
  it('F14', () => { expect(readShared('workflow-schema.ts')).toContain('modeling') })
  it('F15', () => { expect(readShared('workflow-schema.ts')).toContain('writing') })
  it('F16', () => { expect(readShared('workflow-schema.ts')).toContain('review') })
  it('F17', () => { expect(readShared('workflow-schema.ts')).toContain('draft') })
  it('F18', () => { expect(readShared('workflow-schema.ts')).toContain('completed') })
  it('F19', () => { expect(read('project-manager.ts')).toContain('class') })
  it('F20', () => { expect(read('project-manager.ts')).toContain('createProject') })
  it('F21', () => { expect(read('project-manager.ts')).toContain('getProject') })
  it('F22', () => { expect(read('project-manager.ts')).toContain('updateProject') })
  it('F23', () => { expect(read('project-manager.ts')).toContain('addMilestone') })
  it('F24', () => { expect(read('project-manager.ts')).toContain('addTask') })
  it('F25', () => { expect(read('project-manager.ts')).toContain('updateTaskStatus') })
  it('F26', () => { expect(read('project-manager.ts')).toContain('getProgress') })
  it('F27', () => { expect(read('project-manager.ts')).toContain('listProjects') })
  it('F28', () => { expect(read('project-manager.ts')).toContain('size()') })
  it('F29', () => { expect(read('project-manager.ts')).toContain('clear()') })
  it('F30', () => { expect(read('project-manager.ts')).toContain('snapshot') })
  it('F31', () => { expect(read('project-manager.ts')).toContain('cloneProject') })
  it('F32', () => { expect(read('workflow-engine.ts')).toContain('class') })
  it('F33', () => { expect(read('workflow-engine.ts')).toContain('execute') })
  it('F34', () => { expect(read('workflow-engine.ts')).toContain('WorkflowExecutionResult') })
  it('F35', () => { expect(read('workflow-engine.ts')).toContain('workflowId') })
  it('F36', () => { expect(read('workflow-engine.ts')).toContain('executedSteps') })
  it('F37', () => { expect(read('workflow-engine.ts')).toContain('outputs') })
  it('F38', () => { expect(read('workflow-engine.ts')).toContain('confidence') })
  it('F39', () => { expect(read('workflow-engine.ts')).toContain('errors') })
  it('F40', () => { expect(read('research-event-bus.ts')).toContain('class') })
  it('F41', () => { expect(read('research-event-bus.ts')).toContain('emit') })
  it('F42', () => { expect(read('research-event-bus.ts')).toContain('subscribe') })
  it('F43', () => { expect(read('research-event-bus.ts')).toContain('getHistory') })
  it('F44', () => { expect(read('research-event-bus.ts')).toContain('clear') })
  it('F45', () => { expect(read('research-event-bus.ts')).toContain('Map<') })
  it('F46', () => { expect(read('project-templates.ts')).toContain('new-paper') })
  it('F47', () => { expect(read('project-templates.ts')).toContain('dataset-analysis') })
  it('F48', () => { expect(read('project-templates.ts')).toContain('experimental-optimization') })
  it('F49', () => { expect(read('project-agent-adapter.ts')).toContain('dispatchProjectTask') })
  it('F50', () => { expect(read('project-agent-adapter.ts')).toContain('dispatchAllReady') })
  it('F51', () => { expect(read('project-agent-adapter.ts')).toContain('validAgentRole') })
  it('F52', () => { expect(read('project-agent-adapter.ts')).toContain('coordinate') })
  it('F53', () => { expect(read('project-agent-adapter.ts')).toContain('ProjectManager') })
  it('F54', () => { expect(read('project-agent-adapter.ts')).toContain('AgentTask') })
  it('F55', () => { expect(read('project-agent-adapter.ts')).toContain('updateTaskStatus') })
  it('F56', () => { expect(read('project-agent-adapter.ts')).toContain('dependencies') })
  it('F57', () => { expect(read('project-agent-adapter.ts')).toContain('completed') })
})
