import type { MbrpInput } from '../mbrp-types';

interface ProjectRecord {
  id: string;
  name: string;
  description?: string;
  owner_id?: string;
  status?: string;
  start_date?: string;
  end_date?: string;
  source_updated_at?: string;
  [k: string]: unknown;
}

interface TaskRecord {
  id: string;
  project_id?: string;
  milestone_id?: string;
  title: string;
  description?: string;
  status?: string;
  priority?: string;
  assignee_id?: string;
  due_date?: string;
  source_updated_at?: string;
  [k: string]: unknown;
}

const TASK_STATUS_NORMALIZATION: Record<string, string> = {
  todo: 'in_progress',
  pending: 'in_progress',
  in_progress: 'in_progress',
  done: 'done',
  completed: 'done',
  cancelled: 'cancelled',
};

function normalizeTaskStatus(s: string | undefined): string {
  if (!s) return 'in_progress';
  return TASK_STATUS_NORMALIZATION[s.toLowerCase()] ?? s;
}

export interface ConvertProjectsResult {
  entities: NonNullable<MbrpInput['entities']>['projects'];
  files: MbrpInput['files'];
}

export function convertProjects(
  projects: ProjectRecord[],
  tasks: TaskRecord[],
): ConvertProjectsResult {
  const files: MbrpInput['files'] = [];
  const entities: NonNullable<MbrpInput['entities']>['projects'] = [];

  for (const p of projects) {
    entities.push({
      id: p.id,
      name: p.name,
      description: p.description,
      owner_id: p.owner_id,
      status: p.status,
    });

    const overview = renderOverview(p);
    files.push({ path: `projects/${p.id}/overview.md`, content: overview });

    const projectTasks = tasks.filter((t) => t.project_id === p.id);
    const workItems = {
      projectId: p.id,
      generatedAt: p.source_updated_at ?? '1970-01-01T00:00:00Z',
      items: projectTasks.map((t) => ({
        id: t.id,
        title: t.title,
        description: t.description,
        status: normalizeTaskStatus(t.status),
        priority: t.priority,
        assignee_id: t.assignee_id,
        due_date: t.due_date,
        updated_at: t.source_updated_at,
      })),
    };
    files.push({
      path: `projects/${p.id}/work-items.json`,
      content: JSON.stringify(workItems, null, 2),
    });

    const timeline = {
      projectId: p.id,
      start: p.start_date ?? null,
      end: p.end_date ?? null,
      milestones: projectTasks
        .filter((t) => t.due_date)
        .map((t) => ({
          task_id: t.id,
          title: t.title,
          due_date: t.due_date,
        }))
        .sort((a, b) =>
          String(a.due_date).localeCompare(String(b.due_date)),
        ),
    };
    files.push({
      path: `projects/${p.id}/timeline.json`,
      content: JSON.stringify(timeline, null, 2),
    });
  }

  return { entities, files };
}

function renderOverview(p: ProjectRecord): string {
  return [
    `# ${p.name}`,
    '',
    p.description ?? '_No description_',
    '',
    '## Project metadata',
    '',
    `- **Project ID**: ${p.id}`,
    `- **Owner**: ${p.owner_id ?? '_unknown_'}`,
    `- **Status**: ${p.status ?? '_unknown_'}`,
    `- **Start**: ${p.start_date ?? '_unknown_'}`,
    `- **End**: ${p.end_date ?? '_unknown_'}`,
    `- **Last updated**: ${p.source_updated_at ?? '_unknown_'}`,
    '',
    '> Generated by MicroBubble Desktop adaptive migration. Edit locally; web side is read-only.',
  ].join('\n');
}
